name: 'snowflake_setup'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=1.0.0"
profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"